# Generated by Django 4.2.7 on 2023-11-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
        ('user', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerName', models.CharField(max_length=50, verbose_name='Bilgisayar Adı')),
                ('userName', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
                ('serialNumber', models.CharField(max_length=50, verbose_name='Seri No')),
                ('lanMac', models.CharField(max_length=50, verbose_name='LAN MAC')),
                ('wifiMac', models.CharField(max_length=50, verbose_name='Wİ-Fİ MAC')),
                ('windows', models.CharField(max_length=50, verbose_name='WİNDOWS')),
                ('office', models.CharField(max_length=50, verbose_name='Ofis')),
                ('licenceCodeOfOffice', models.CharField(max_length=50, verbose_name='Lisans Kodu Ofis')),
                ('connectOfficeToMail', models.CharField(max_length=50, verbose_name='Ofis Bağlı E-Posta Adresi')),
                ('debitNumber', models.CharField(max_length=50, verbose_name='Zimmet No')),
                ('remoteDesktopConnection', models.CharField(max_length=50, verbose_name='Uzaktan Masaüstü Bağlantısı')),
                ('debitDate', models.DateField(verbose_name='Zimmet Tarihi')),
                ('id_brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brands', verbose_name='Marka Model')),
                ('id_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.types', verbose_name='Cinsi')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='Kullanıcı')),
            ],
        ),
    ]
