# Generated by Django 4.2.7 on 2023-11-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        ('user', '0001_initial'),
        ('brand', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='computerName',
            field=models.CharField(max_length=50, null=True, verbose_name='Bilgisayar Adı'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='connectOfficeToMail',
            field=models.CharField(max_length=50, null=True, verbose_name='Ofis Bağlı E-Posta Adresi'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='debitDate',
            field=models.DateField(null=True, verbose_name='Zimmet Tarihi'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='debitNumber',
            field=models.CharField(max_length=50, null=True, verbose_name='Zimmet No'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brands', verbose_name='Marka Model'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='type.types', verbose_name='Cinsi'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lanMac',
            field=models.CharField(max_length=50, null=True, verbose_name='LAN MAC'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='licenceCodeOfOffice',
            field=models.CharField(max_length=50, null=True, verbose_name='Lisans Kodu Ofis'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='office',
            field=models.CharField(max_length=50, null=True, verbose_name='Ofis'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='remoteDesktopConnection',
            field=models.CharField(max_length=50, null=True, verbose_name='Uzaktan Masaüstü Bağlantısı'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serialNumber',
            field=models.CharField(max_length=50, null=True, verbose_name='Seri No'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='userName',
            field=models.CharField(max_length=50, null=True, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='wifiMac',
            field=models.CharField(max_length=50, null=True, verbose_name='Wİ-Fİ MAC'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='windows',
            field=models.CharField(max_length=50, null=True, verbose_name='WİNDOWS'),
        ),
    ]
